---
- name: Playbook for VPC
  hosts: localhost
  gather_facts: no
  vars_files:
    - configurations/regions
  tasks:
    - name: Collect VPC info
      ec2_vpc_net_facts:
        region: "{{region}}"
        filters:
          "tag:Task": VPC
      register: VPC1

    - name: create NG
      ec2_vpc_nat_gateway:
        region: "{{region}}"
        subnet_id: "{{subnet_id}}"
        allocation_id: "{{allocation_id}}"
        state: present
      register: igw
