---
- name: Playbook for VPC
  hosts: localhost
  tasks:
    - name: Create a VPC
      ec2_vpc_net:
        name: Team-1
        cidr_block: 10.10.0.0/16
        region: us-east-1
        state: present
       
